import type { Metadata } from "next";
import {Dancing_Script, Great_Vibes} from "next/font/google";
import "./globals.css";

const greatVibes = Great_Vibes({
  subsets: ['latin'], // Incluye solo caracteres necesarios
  weight: '400', // Especifica los pesos que vas a usar
  variable: '--font-great-vibes', // Define una variable CSS
});;

const dancingScript = Dancing_Script({
  subsets: ['latin'],
  variable: '--font-dancing-script',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${greatVibes.variable} ${dancingScript.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
